version: '3.5'
services:
  trivia-db:
    image: "postgres"
    hostname: "trivia-db"
    container_name: trivia-db
    environment:
      - PGPASSWORD=postgres
      - POSTGRES_DB=trivia-art
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5445
      - PGPORT=5445
    ports:
      - "5445:5445"
    networks:
      - trivia-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 10

  trivia-redis:
    image: "bitnami/redis:latest"
    hostname: "trivia-redis"
    container_name: trivia-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      - trivia-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      interval: 2s
      retries: 10


networks:
  trivia-network:
    name: trivia-network
    driver: bridge
